### ISSUE TITLE
Messages from bridge not going out to hangouts

### ISSUE THREAD

**Issue by pbialasiewicz** [matrix-hacks/matrix-puppet-hangouts#12]
I installed the hangouts bridge and connected it to my HS. Everybody can see the hangouts messages that are sent using the native client. I can see the messages sent to my hangouts account using the bridge on my riot client. But the messages that I'm sending to a hangouts members using the riot client can only be seen on my riot client(I cannot see them in the hangouts client and the other person also cannot see those messages). It looks like the messages are not traveling from riot to hangouts. 
I tired reinstalling the matrix bridge from scratch, restarting the synapse server, restart the riot client, deleting the conversation in hangouts. I tested this for existing conversations and for new ones. In every case I'm having the same problem.

**Comment by Sorunome** [comment]
The issue was a mis-configured appservice, using `https://localhost:8090` instead of `http://localhost:8090`
